package com.lc.tt.lc.core.entity;

import java.io.Serializable;
import java.util.Date;

public class TSupplier implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_supplier_Id
     *
     * @mbg.generated
     */
    private String cSupplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_supplier_Name
     *
     * @mbg.generated
     */
    private String cSupplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_project_id
     *
     * @mbg.generated
     */
    private String cProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_supplier_result
     *
     * @mbg.generated
     */
    private Integer cSupplierResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_site_userid
     *
     * @mbg.generated
     */
    private String cSiteUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_site_main_userid
     *
     * @mbg.generated
     */
    private String cSiteMainUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_site_manager_userid
     *
     * @mbg.generated
     */
    private String cSiteManagerUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_site_fmajordomo_userid
     *
     * @mbg.generated
     */
    private String cSiteFmajordomoUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_site_majordomo_userid
     *
     * @mbg.generated
     */
    private String cSiteMajordomoUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_ststem_num
     *
     * @mbg.generated
     */
    private String cStstemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.c_part_num
     *
     * @mbg.generated
     */
    private String cPartNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_supplier
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.pid
     *
     * @return the value of t_supplier.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.pid
     *
     * @param pid the value for t_supplier.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.id
     *
     * @return the value of t_supplier.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.id
     *
     * @param id the value for t_supplier.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.create_at
     *
     * @return the value of t_supplier.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.create_at
     *
     * @param createAt the value for t_supplier.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.update_at
     *
     * @return the value of t_supplier.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.update_at
     *
     * @param updateAt the value for t_supplier.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_supplier_Id
     *
     * @return the value of t_supplier.c_supplier_Id
     *
     * @mbg.generated
     */
    public String getcSupplierId() {
        return cSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_supplier_Id
     *
     * @param cSupplierId the value for t_supplier.c_supplier_Id
     *
     * @mbg.generated
     */
    public void setcSupplierId(String cSupplierId) {
        this.cSupplierId = cSupplierId == null ? null : cSupplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_supplier_Name
     *
     * @return the value of t_supplier.c_supplier_Name
     *
     * @mbg.generated
     */
    public String getcSupplierName() {
        return cSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_supplier_Name
     *
     * @param cSupplierName the value for t_supplier.c_supplier_Name
     *
     * @mbg.generated
     */
    public void setcSupplierName(String cSupplierName) {
        this.cSupplierName = cSupplierName == null ? null : cSupplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_project_id
     *
     * @return the value of t_supplier.c_project_id
     *
     * @mbg.generated
     */
    public String getcProjectId() {
        return cProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_project_id
     *
     * @param cProjectId the value for t_supplier.c_project_id
     *
     * @mbg.generated
     */
    public void setcProjectId(String cProjectId) {
        this.cProjectId = cProjectId == null ? null : cProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_supplier_result
     *
     * @return the value of t_supplier.c_supplier_result
     *
     * @mbg.generated
     */
    public Integer getcSupplierResult() {
        return cSupplierResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_supplier_result
     *
     * @param cSupplierResult the value for t_supplier.c_supplier_result
     *
     * @mbg.generated
     */
    public void setcSupplierResult(Integer cSupplierResult) {
        this.cSupplierResult = cSupplierResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_site_userid
     *
     * @return the value of t_supplier.c_site_userid
     *
     * @mbg.generated
     */
    public String getcSiteUserid() {
        return cSiteUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_site_userid
     *
     * @param cSiteUserid the value for t_supplier.c_site_userid
     *
     * @mbg.generated
     */
    public void setcSiteUserid(String cSiteUserid) {
        this.cSiteUserid = cSiteUserid == null ? null : cSiteUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_site_main_userid
     *
     * @return the value of t_supplier.c_site_main_userid
     *
     * @mbg.generated
     */
    public String getcSiteMainUserid() {
        return cSiteMainUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_site_main_userid
     *
     * @param cSiteMainUserid the value for t_supplier.c_site_main_userid
     *
     * @mbg.generated
     */
    public void setcSiteMainUserid(String cSiteMainUserid) {
        this.cSiteMainUserid = cSiteMainUserid == null ? null : cSiteMainUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_site_manager_userid
     *
     * @return the value of t_supplier.c_site_manager_userid
     *
     * @mbg.generated
     */
    public String getcSiteManagerUserid() {
        return cSiteManagerUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_site_manager_userid
     *
     * @param cSiteManagerUserid the value for t_supplier.c_site_manager_userid
     *
     * @mbg.generated
     */
    public void setcSiteManagerUserid(String cSiteManagerUserid) {
        this.cSiteManagerUserid = cSiteManagerUserid == null ? null : cSiteManagerUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_site_fmajordomo_userid
     *
     * @return the value of t_supplier.c_site_fmajordomo_userid
     *
     * @mbg.generated
     */
    public String getcSiteFmajordomoUserid() {
        return cSiteFmajordomoUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_site_fmajordomo_userid
     *
     * @param cSiteFmajordomoUserid the value for t_supplier.c_site_fmajordomo_userid
     *
     * @mbg.generated
     */
    public void setcSiteFmajordomoUserid(String cSiteFmajordomoUserid) {
        this.cSiteFmajordomoUserid = cSiteFmajordomoUserid == null ? null : cSiteFmajordomoUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_site_majordomo_userid
     *
     * @return the value of t_supplier.c_site_majordomo_userid
     *
     * @mbg.generated
     */
    public String getcSiteMajordomoUserid() {
        return cSiteMajordomoUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_site_majordomo_userid
     *
     * @param cSiteMajordomoUserid the value for t_supplier.c_site_majordomo_userid
     *
     * @mbg.generated
     */
    public void setcSiteMajordomoUserid(String cSiteMajordomoUserid) {
        this.cSiteMajordomoUserid = cSiteMajordomoUserid == null ? null : cSiteMajordomoUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_ststem_num
     *
     * @return the value of t_supplier.c_ststem_num
     *
     * @mbg.generated
     */
    public String getcStstemNum() {
        return cStstemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_ststem_num
     *
     * @param cStstemNum the value for t_supplier.c_ststem_num
     *
     * @mbg.generated
     */
    public void setcStstemNum(String cStstemNum) {
        this.cStstemNum = cStstemNum == null ? null : cStstemNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.c_part_num
     *
     * @return the value of t_supplier.c_part_num
     *
     * @mbg.generated
     */
    public String getcPartNum() {
        return cPartNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.c_part_num
     *
     * @param cPartNum the value for t_supplier.c_part_num
     *
     * @mbg.generated
     */
    public void setcPartNum(String cPartNum) {
        this.cPartNum = cPartNum == null ? null : cPartNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", id=").append(id);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", cSupplierId=").append(cSupplierId);
        sb.append(", cSupplierName=").append(cSupplierName);
        sb.append(", cProjectId=").append(cProjectId);
        sb.append(", cSupplierResult=").append(cSupplierResult);
        sb.append(", cSiteUserid=").append(cSiteUserid);
        sb.append(", cSiteMainUserid=").append(cSiteMainUserid);
        sb.append(", cSiteManagerUserid=").append(cSiteManagerUserid);
        sb.append(", cSiteFmajordomoUserid=").append(cSiteFmajordomoUserid);
        sb.append(", cSiteMajordomoUserid=").append(cSiteMajordomoUserid);
        sb.append(", cStstemNum=").append(cStstemNum);
        sb.append(", cPartNum=").append(cPartNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}